// Level maps. One character = one 4×4 m tile.
//  #  crystal wall            .  floor island           (space)  void — fall!
//  S  start                   E  exit portal            *  star shard (need all 3)
//  ~  void lane               M  moving platform (rides its ~ lane)
//  B  bounce pad (clears up to 3 void tiles)
//  C  crumbling tile — collapses shortly after you step on it, reforms later
//  D  patrol drone — sweeps its corridor, touching it costs a heart
//  R  rotating laser — jump over the beam
//  X  spike trap — pulses up and down, cross when it's retracted
//  H  hidden relic — optional collectible, saved to your Collection
//  I  insect (jungle) — wanders the maze, chases you when it sees you, then winds up and lunges
// Optional per level: dash (enables the dash + stamina bar), chapter (default 1), theme ('jungle' = island/nature look), relicIds (relic models to reuse), hearts (max hearts cap), hazard (laser/drone speed ×)
export const TILE = 4;

export const LEVELS = [
  {
    name: 'The Drift', par: 75,
    sub: 'Find the three star shards to wake the portal.',
    relics: ['Driftglass Compass', 'Echo of the First Star'],
    palette: { sky1: 0x2a0e3a, sky2: 0x0a1a3a, neb: [0.85, 0.25, 0.55], neb2: [0.2, 0.35, 0.9], crystal: 0x9b6bff, trim: 0x5ce1ff, fog: 0x140b22, sun: 0xffc9e8, planet: 0xff7a9c, aur: [0.3, 1.0, 0.7] },
    map: [
      '#############',
      '#S....#....H#',
      '#.###.#.###.#',
      '#.#*..#...#.#',
      '#.#.#####.#.#',
      '#...#...#.#.#',
      '###.#.#.#.#.#',
      '#...#.#...#*#',
      '#.###.#####.#',
      '#.#H..#.....#',
      '#.#.###.###.#',
      '#*..#...D.#E#',
      '#############',
    ],
  },
  {
    name: 'Nebula Gardens', par: 110,
    sub: 'Broken paths and crumbling stone. Sprint, then jump.',
    relics: ['Garden Seedlight', 'Tidal Bloom'],
    palette: { sky1: 0x06283a, sky2: 0x1a0b33, neb: [0.15, 0.8, 0.75], neb2: [0.55, 0.25, 0.95], crystal: 0x46ffc8, trim: 0x9d7bff, fog: 0x07161f, sun: 0xb8fff0, planet: 0x6fe3ff, aur: [0.6, 0.4, 1.0] },
    map: [
      '###############',
      '#S.. C..#.....#',
      '####.##.#.###.#',
      '#*.. ...#.#*#.#',
      '###.###.#.#.#.#',
      '#...#.C ..#...#',
      '#.###.#####.###',
      '#.#...# H #...#',
      '#.#.###   ###.#',
      '#... .#..X....#',
      '#####.#.#####.#',
      '#*... . .# H .#',
      '#.#####.##.## #',
      '#...D...#....E#',
      '###############',
    ],
  },
  {
    name: 'The Core', par: 140,
    sub: 'Ride drifting stones, bounce the gaps, hop the laser.',
    relics: ['Ember of the Core', 'Magma Hourglass'],
    palette: { sky1: 0x3a1206, sky2: 0x14062a, neb: [1.0, 0.45, 0.2], neb2: [0.7, 0.15, 0.6], crystal: 0xff8a4c, trim: 0xffd36e, fog: 0x1c0a0a, sun: 0xffd9a8, planet: 0xffb36b, aur: [1.0, 0.5, 0.3] },
    map: [
      '#################',
      '#S...#...~~~M..*#',
      '###.##.##########',
      '#.....B  .#.....#',
      '#.#########.###.#',
      '#.#*..#..R..#...#',
      '#.#.#.#.#####.###',
      '#...#...# H #...#',
      '#####.###   ###.#',
      '#*..M~~~~.....#.#',
      '###.#####.###.#.#',
      '#H..#.X.#...#...#',
      '#.###.#.###.#####',
      '#.....#...B   ..E',
      '#################',
    ],
  },
  {
    name: 'Shattered Halo', par: 165,
    sub: 'The ice cracks beneath you. Drones patrol the halls.',
    relics: ['Frozen Halo Shard', 'Glacier Lantern'],
    palette: { sky1: 0x0a2440, sky2: 0x050a1a, neb: [0.35, 0.65, 1.0], neb2: [0.5, 0.6, 0.9], crystal: 0x8fd8ff, trim: 0xe0f4ff, fog: 0x06101c, sun: 0xe6f4ff, planet: 0x9fd0ff, aur: [0.4, 1.0, 0.9] },
    map: [
      '#################',
      '#S..C.C..#.....H#',
      '#.#####.##.###.##',
      '#...#....D.#...##',
      '###.#.######.#.##',
      '#*..#.C. C...#.##',
      '#.###.#####.##..#',
      '#.....#*..X.....#',
      '#####.#.#######.#',
      '#.D...#.#   #...#',
      '#.#####.# H #.###',
      '#.#.....#   #...#',
      '#.#.######..###.#',
      '#*#...X.....#...#',
      '#.#####.###.#.#.#',
      '#.......#..D..#E#',
      '#################',
    ],
  },
  {
    name: 'Laser Garden', par: 175,
    sub: 'Beams sweep the paths. Time every jump.',
    relics: ['Prism Thorn', 'Laser Lotus'],
    palette: { sky1: 0x3a0620, sky2: 0x10041a, neb: [1.0, 0.2, 0.45], neb2: [0.6, 0.1, 0.8], crystal: 0xff4f8b, trim: 0xff9ad0, fog: 0x16050d, sun: 0xffb3cf, planet: 0xff5c8a, aur: [1.0, 0.3, 0.8] },
    map: [
      '#################',
      '#S.....#...R...H#',
      '#.###.##.#####.##',
      '#.#X#....#...#..#',
      '#.#.####.#.#.##.#',
      '#...#*...R.#....#',
      '###.######.######',
      '#...~~~M...X...*#',
      '#.#########.#####',
      '#.....R.....#H..#',
      '#####.#####.#.#.#',
      '#*..X.#####...#.#',
      '#.###.#####.###.#',
      '#...#.#####.#...#',
      '###.#.#####.#.###',
      '#.....X..D.....E#',
      '#################',
    ],
  },
  {
    name: "Aurora's Heart", par: 230, dash: true,
    sub: 'Everything you have learned. Reach the heart of the aurora.',
    relics: ['Heart of Aurora', 'Northern Crown'],
    palette: { sky1: 0x061a2a, sky2: 0x12062a, neb: [0.3, 1.0, 0.6], neb2: [0.8, 0.4, 1.0], crystal: 0xb69cff, trim: 0x7fffd4, fog: 0x060c16, sun: 0xe8fff4, planet: 0x7fd4ff, aur: [0.35, 1.0, 0.65] },
    map: [
      '###################',
      '#S..#.....R.....#H#',
      '#.#.#.#########.#.#',
      '#.#...#*..X..#..C.#',
      '#.#####.####.#.####',
      '#...D.#.#..C  .#..#',
      '###.#.#.#.####.#.##',
      '#*#.#...#....R.#..#',
      '#.#.#####.######.##',
      '#.#...~~~M.....#..#',
      '#.###.####.###.#.##',
      '#...#..X.#...#.B  E',
      '###.####.###.#.####',
      '#H#......#.D...#..#',
      '#.######.#.#####.##',
      '#...C .#.#...X...*#',
      '#.####.#.#####.####',
      '#......C.......D..#',
      '###################',
    ],
  },
  {
    name: 'Level Impossible', par: 360,
    sub: 'The final trial of Chapter 1. Lasers, spikes and drones everywhere.',
    relics: ['Shard of the Impossible', 'Crown of Chapter One'],
    relicIds: [3, 8], hearts: 2, hazard: 1.25,
    palette: { sky1: 0x1a0306, sky2: 0x05020c, neb: [1.0, 0.12, 0.18], neb2: [0.45, 0.05, 0.6], crystal: 0xff3b4f, trim: 0xffb14a, fog: 0x0c0306, sun: 0xffc2b0, planet: 0xff2e3e, aur: [1.0, 0.25, 0.2] },
    map: [
      '#########################',
      '#S.X.R.C C.#...X...R....#',
      '#.#######.##.#####.###.##',
      '#.#...D...#..#*..X.#...##',
      '#.#.#####.#.##.###.#.####',
      '#.X.#.R.#.C .#..R..#..X.#',
      '###.#...#.####.#####.##.#',
      '#H..#.X.#....D.....#....#',
      '#.###.#.######.###.#.####',
      '#.~~M.#...R..X.#H#.C C..#',
      '#.#####.#####.##.#.####.#',
      '#...X...#*..#..X.#...R..#',
      '###.###.#.#.####.###.####',
      '#.#.#.R.#.#....D...#....#',
      '#.#.#...#.####.###.#.##.#',
      '#.C.#.X.#.C .#...#.X..#.#',
      '#.#.###.#.#.X#.R.#.##.#.#',
      '#...#...#.#..#...#..#.#.#',
      '#.###.###.##.#####.##.#.#',
      '#.#...D...#..R.X.C ....B#',
      '#.#.#####.#.#######.### #',
      '#.X..R..C .*#.D...X.M~. #',
      '#####.#####.#.#####.###.#',
      '#.....X...R...C C...D..E#',
      '#########################',
    ],
  },
  {
    name: 'Whispering Grove', par: 270, chapter: 2, theme: 'jungle', demo: true, dash: true,
    sub: 'A vast island forest. Trees block the way, thorns wait in the grass, and something is buzzing…',
    relics: ['Amber Heartseed', 'Moonleaf Totem'],
    relicIds: [12, 13],
    palette: { sky1: 0x0b1a2e, sky2: 0x04060d, neb: [0.2, 0.6, 0.45], neb2: [0.45, 0.3, 0.85], crystal: 0x7ddc5a, trim: 0xd8ff7a, fog: 0x0a1612, sun: 0xfff1c9, planet: 0x9be07a, aur: [0.55, 1.0, 0.45] },
    map: [
      '#################################',
      '#*..#.....#.#.X.....#*..........#',
      '###.#.#.#.#.#.#.###.#####.#####.#',
      '#...#.#.#.#.#.#...#...#...#..X..#',
      '#.###.#.#.#.#.###.###.#.###.#####',
      '#.#.....#.#...#.X.#.#.#I........#',
      '#.###.###.#.###.###.#.#.#######.#',
      '#...#...#....I#...#.#.#.......#.#',
      '###.###.#####.###.#.#.#X#######.#',
      '#.#...#.....#.....#...#.#...#..I#',
      '#.###.###.#.#.#####.###.#.#.#.#.#',
      '#...#...#.#.....#...#...#.#.#.#.#',
      '#.#####.#.#####.#.#######...#.#.#',
      '#.#...X.#....H#.#...X.....#.#X#.#',
      '#.#.#####.#####.###########.#.#.#',
      '#S#.#H....#.X.#.......#...#...#.#',
      '#.#.#######.#I#.#####.#.#######.#',
      '#.#.........#.........#..X....#.#',
      '#.#########################.#.#.#',
      '#.#..I.X....#...............#.#.#',
      '#.#.#.###.###.#########.#####.#.#',
      '#.#.#...#.#...#...X....I#.....#.#',
      '#.#.#.#.###.###.###.###########.#',
      '#.#...#.#...#.#...#...#.....#...#',
      '#.###.X.#.###.###.#.#.#X###.#.###',
      '#.....#...#.....#...#.#.#.#..I#.#',
      '#.#########.###.#####.#.#.#####.#',
      '#.X...I.....#......*#..........E#',
      '#################################',
    ],
  },
];
